version: '3.8'
services:
  postgresdb:
    image: postgres
    environment:
      - POSTGRES_USER=jonataslaet
      - POSTGRES_PASSWORD=blendo273
      - POSTGRES_DB=dblaetstore
    ports:
      - '5432:5432'
